finish writing
dimitryzub/serpapi-blog-posts-archive pull request #11
Opened 2022-05-16 16:45 UTC by Mykhailo-Zub

2022-05-19 05:04 UTC, dimitryzub requested changes
@Mykhailo-Zub, thank you for your work ☀️

The code looks good to me, great job on scraping images with regex as well. There's only a text formatting to be done. Other than that, everything looks good to me.

Next steps:
1. Make a draft on serpapi ghost.
2. Share this draft here in the comments, via <kbd>Preview</kbd> -> <kbd>open in a new tab</kbd>  -> <kbd>copy the link</kbd> and paste here.
3. I'll review it one more time. If ok, publish to serpapi blog, and other platforms if you can.


@ilyazub, when you have time, could you please add Misha to https://dev.to/serpapi team, so he can publish this blog post there?

![image](https://user-images.githubusercontent.com/78694043/169211904-e4ea8c0b-76e5-4a6b-adda-0d27b56a9205.png)

2022-05-19 07:57 UTC, Mykhailo-Zub commented on Google/google_news/google_news_tab/javascript/withSerpApi.js
> +// https://dev.to/mikhailzub/how-to-scrape-google-news-with-nodejs-3el6-temp-slug-8721582?preview=1edd6335ce816828245e9c39bcb357a0659ed993467a7d129d31619d42fd4b71c9cbbfbc9339fb350aa89fd78e72ba6564e96
I have removed the link here and will leave a link to the published post in the comments here.

2022-05-19 08:24 UTC, Mykhailo-Zub commented
https://serpapi.com/blog/p/deb09696-facc-44ec-a9d7-717f720fe2fd/

2022-05-19 09:09 UTC, dimitryzub commented
@Mykhailo-Zub, regarding linking an issue.

You can just write: `Resolves #11` (without a code block as here) or something similar.

2022-05-20 10:26 UTC, dimitryzub requested changes
Thanks, @Mykhailo-Zub for the changes 👍🏻 

However, there are a few changes that haven't been changed. I mentioned them again and add additional suggestions to text formatting and code explanation.

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +            const pattern = /s='(?<img>[^']+)';\w+\s\w+=\['(?<id>\w+_\d+)'];/gm;
I don't see that you added a regex example showing what your regex is extracting from the HTML. Could you add a link to the example?

https://github.com/dimitryzub/serpapi-blog-posts-archive/pull/11/files#r876584460

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +            const images = [...data.matchAll(pattern)].map(({ groups }) => ({ id: groups.id, img: groups.img.replace('\\x3d', '') }))
`[...data]` tell more to the readers about what is `...` and what it's doing. 

When explaining, try to think that the people who will be reading it have no idea about JS and web scraping.

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +                    link: $(el).attr('href'),
In the explanation section, tell more to the reader about `attr()` and what it's doing. You can also reference a link to the function from the `cheerio` source code showing what it's doing, or from their docs.

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +Now we can launch our parser. To do this enter `node YOUR_FILE_NAME` in your command line. Where "YOUR_FILE_NAME" is the name of your ".js" file
I don't see applied changes to [previously suggested changes](https://github.com/dimitryzub/serpapi-blog-posts-archive/pull/11/files#r876586124).

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +```javascript
I don't see `'''javascript` being replaced with the correct `'''json` syntax highlight.

https://github.com/dimitryzub/serpapi-blog-posts-archive/pull/11/files#r876586221

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +First we need to install "google-search-results-nodejs". To do this you need to enter in your console:
Did you apply this change?

https://github.com/dimitryzub/serpapi-blog-posts-archive/pull/11/files#r876587282

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +The difference is that all that needs to be done is just to iterate over a ready made, structured JSON instead of coding everything from scratch, and selecting correct selectors which could be time c
Did you apply this change?

https://github.com/dimitryzub/serpapi-blog-posts-archive/pull/11/files#r876586703

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +  tbm: "nws"                                            // parameter defines the type of search you want to do ("nws" means news)
```suggestion
  engine: "google",             // search engine
  q: searchString,              // search query
  google_domain: "google.com",  // google domain: google.com, google.de, google.fr..
  gl: "us",                     // parameter defines the country to use for the Google search
  hl: "en",                     // Parameter defines the language to use for the Google search
  tbm: "nws"                    // parameter defines the type of search you want to do ("nws" means news)
```

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +* tbm - parameter defines the type of search you want to do
```suggestion
```

Let's delete it as it's already commented in the code. It will be a duplicate explanation.

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +```javascript
I don't see `'''javascript` being replaced with the correct `'''json` syntax highlight.

https://github.com/dimitryzub/serpapi-blog-posts-archive/pull/11/files#r876588637

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +* [SerpApi Playground](https://serpapi.com/playground?q=elon+musk&gl=us&hl=en&tbm=nws)
```suggestion
* [Code in the online IDE](https://replit.com/@MikhailZub/Google-News-Tab-scrape-NodeJS-SerpApi#index.js) 
* [SerpApi Playground](https://serpapi.com/playground?q=elon+musk&gl=us&hl=en&tbm=nws)
* [Google News Result API](https://serpapi.com/news-results)
```

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +* axios - library for requesting the desired html document;
Add npm links to `cheerio` and `axios` so people would know the correct package links.

2022-05-20 10:26 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +                    source: $(el).find('.CEMjEf span').text().trim(),
In the explanation section, explain what `find()` is doing. If you want, leave a link that will be referencing this function in the documentation or from the `cheerio` source code.

2022-05-20 10:27 UTC, dimitryzub commented on Google/google_news/google_news_tab/javascript/google_news_scrape.md
> +[Code in the online IDE](https://replit.com/@MikhailZub/Google-News-Tab-scrape-NodeJS-SerpApi#index.js) • [SerpApi Playground](https://serpapi.com/playground?q=elon+musk&gl=us&hl=en&tbm=nws)
@Mykhailo-Zub 👍🏻 

Feel free to add or leave as is.

2022-05-20 15:47 UTC, Mykhailo-Zub commented
[Updated draft](https://serpapi.com/blog/p/deb09696-facc-44ec-a9d7-717f720fe2fd/) check it please

2022-05-23 05:26 UTC, dimitryzub approved these changes
@Mykhailo-Zub super good job explaining each part of the code. Thank you for adding an [example of what is being matched by regex pattern](https://regex101.com/r/pMd0yx/1) 👍🏻

Let's stick to such an explanation in every other blog post, and continue to improve it. This is more valuable to the reader and a reputation to you.

____

A minor thing I already fixed inside the Ghost draft. When showing JSON output, use double quotes `"` instead of a single quote `'`, otherwise, the result will be like so:

|singe quote `'`|double quote `"`|
|--|--|
|![image](https://user-images.githubusercontent.com/78694043/169748209-0b9b4b99-fbfb-4c8d-9f8d-2677eada753a.png)|![image](https://user-images.githubusercontent.com/78694043/169748231-6dd41347-ff90-4e26-ac25-0ab7a7511433.png)|

To quickly convert JSON output, I'm usually using JSON formatted: https://jsonformatter.curiousconcept.com/

____

### Next steps

1. You can go ahead and publish this blog post to SerpApi.
2. Leave a link to the published blog post in this RP thread.
3. Use markdown from the ghost draft If you want to publish this blog post to other platforms such as dev.to/hashnode/medium, as it has the latest changes for now.

If you are publishing to Medium, write me in telegram, and I'll record you a small video explaining how to correctly copy-paste blog post from Ghost to Medium as it has some nuances.

2022-05-23 07:28 UTC, merged

2022-05-23 07:29 UTC, Mykhailo-Zub commented
https://serpapi.com/blog/how-to-scrape-google-news-with-node-js/