google-play-apps
dimitryzub/serpapi-blog-posts-archive pull request #13
Opened 2022-05-19 10:06 UTC by Mykhailo-Zub

Resolves #12. Check it please.

2022-05-23 05:57 UTC, dimitryzub requested changes
@Mykhailo-Zub thank you for another blog post 👍🏻 The code looks good to me.

Please, add changes as you did in https://github.com/dimitryzub/serpapi-blog-posts-archive/pull/11/commits/022e67554cbc9c80ea16c9d8a45a54cea71d9023, Google News #11 PR, as there's is an identical thing that needs to be done here.

- leave a link reference to the packages and functions in the explanation section.
- explain what each unique function is doing using the markdown table as you did previously, and let's stick to it.
- pay attention to markdown headers `#`. Add space between header and text: `### text`, not: `###text`, as it could cause confusion in some markdown editors. It's an annoying thing but needs to be done.

2022-05-23 14:16 UTC, dimitryzub reviewed
@Mykhailo-Zub, awesome 💯 Thank you for your work. Everything looks good to me.

I've noticed a few typos. They're minor so you can go ahead and publish the blog post, or edit them and publish. You can use [Grammarly ](https://app.grammarly.com/)to get rid of annoying typos 🙂

Let's publish this blog post on May 25, and share published links in this thread.

2022-05-23 14:16 UTC, dimitryzub commented on Google/google_play_store/play_products/apps/javascript/google_play_apps_main_page.md
> +The difference is that all that needs to be done is just to iterate over a ready made, structured JSON instead of coding everything from scratch maintaining, figuring out how to bypass blocks from Go
```suggestion
The difference is that all that needs to be done is just to iterate over a ready-made, structured JSON instead of coding everything from scratch, maintaining, figuring out how to bypass blocks from Google, and selecting correct selectors which could be time-consuming at times. [Check out the playground](https://serpapi.com/playground).
```

2022-05-25 05:33 UTC, dimitryzub commented
@Mykhailo-Zub you can go ahead and merge this PR and publish the blog post. 

Please leave links to the published blog post here.

2022-05-25 07:51 UTC, merged

2022-05-25 07:59 UTC, Mykhailo-Zub commented
https://serpapi.com/blog/how-to-scrape-google-play-apps/
https://medium.com/@mikhail.a.zub/how-to-scrape-google-play-apps-with-node-js-2036612c0ce
https://dev.to/serpapi/how-to-scrape-google-play-apps-with-nodejs-51o8
https://serpapi.hashnode.dev/how-to-scrape-google-play-apps-with-nodejs