Google knowledge graph
dimitryzub/serpapi-blog-posts-archive pull request #15
Opened 2022-05-23 13:36 UTC by Mykhailo-Zub

Resolved #14. 
[Draft](https://serpapi.com/blog/p/ebc95e21-2044-43af-98a5-f0d4adeac01d/)

2022-05-26 08:18 UTC, dimitryzub requested changes
@Mykhailo-Zub Good job on this blog post 😎

I've added a few suggestions to make the blog post even better.

2022-05-26 08:18 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +
Add a note message that the knowledge graph has different layouts so the code you provide works with such layout shown on the screenshot.

```
📌Note: <some text to note about>
```

2022-05-26 08:18 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +The difference is that all that needs to be done is just to iterate over a ready made, structured JSON instead of coding everything from scratch, maintaining, figuring out how to bypass blocks from G
Try to rephrase it a little bit not to copy-paste it each time.

2022-05-26 08:18 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +          allInfo.main = {...allInfo.main, [key]: knowledge_graph[key]}
Does JS have something like the [`get()`](https://www.w3schools.com/python/ref_dictionary_get.asp) dictionary method in Python to return a value if the specified key does not exist? _Default value is None_.

In Python we can call hash key like so: `knowledge_graph["image"]` but it will raise an error if no image is returned.

Two ways of handling in Python:

```python
# try/catch

try:
   image = knowledge_graph["image"]
except:
   image = None
```

Better way which will get rid of `if/else`, `try/except` in case of Python:

```python
image = knowledge_graph.get("image") # defaults to None/Null if no image returned
```

2022-05-26 08:18 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +  }
Describe why you did it and what's the purpose of it. Like "_create a structure for extracted data_" or something similar. To make it more understandable for the reader.

2022-05-26 08:29 UTC, dimitryzub requested changes
Additional changes on selectors.

2022-05-26 08:29 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +        link: $(".I6TXqe .hb8SAc span:nth-child(3) a").attr("href"),
```suggestion
      description: {
        text: $(".LWkfKe+ span").text().trim(),
        source: $(".NJLBac").text().trim(),
        link: $(".NJLBac").attr("href"),
```

Previous selectors doesn't scraped description:

![image](https://user-images.githubusercontent.com/78694043/170449738-a431e5f0-479c-477b-951a-99216110ee50.png)

Suggested selectors:

![image](https://user-images.githubusercontent.com/78694043/170449833-b115e42b-0d5d-42c0-8a2b-e8ac8e29d19c.png)

2022-05-26 09:32 UTC, Mykhailo-Zub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +*<span style="font-size: 15px;">If you don't have Node.js installed, you can download it from [here](https://nodejs.org/en/) and follow the installation [documentation](https://nodejs.dev/learn/intro
> You don't actually need to use <span> tags inside markdown unless you really want to. Why do you use it in this case?

I use `<span>` along with the font size to make the text look like a footnote, i.e. was smaller than normal text.
![Без имени](https://user-images.githubusercontent.com/64033139/170453642-57ac29ce-9d2e-4fe0-9e6d-488b2e78c903.png)

2022-05-26 09:38 UTC, Mykhailo-Zub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +![how-2](https://serpapi.com/blog/content/images/2022/05/how-2.gif)
> Let's make this GIF pretty by removing distracting parts:

How about this thing?
![Без имени1](https://user-images.githubusercontent.com/64033139/170461805-cd5aedd5-2f0e-463e-b77b-0daf50406a04.png)
If I make the capture area narrower, this panel will not fit.

2022-05-26 09:47 UTC, Mykhailo-Zub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +    const pattern = /s='(?<img>[^']+)';\w+\s\w+=\['(?<id>\w+_\d+)'];/gm;
Do you mean I need to add the link in the comment in the code? Because I already wrote it in the code explanation block.

2022-05-26 09:57 UTC, Mykhailo-Zub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +|`$(".I6TXqe .VLkRKc").closest(".UDZeY")`|finds the nearest parent element with class name `UDZeY` in elements with class name `I6TXqe` that have elements with class names `VLkRKc`|
I wanted to explain what mean `closest()` and I don't do this if I use the same method name in the explanation.

2022-05-26 10:26 UTC, Mykhailo-Zub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +          allInfo.main = {...allInfo.main, [key]: knowledge_graph[key]}
In JS I can use `image = knowledge_graph["image"]` that return a value or `undefined`. But in this case, I wrote the data from known keys, like `title, type, website, ...` that repeats in various search results, and the data from unknown keys that I called `main info`. So I need to use `for (in)` and `if/else` statements to get data from all known keys (or skip them) at the beginning and other unknown keys in the end: 
`else {
          allInfo.main = {...allInfo.main, [key]: knowledge_graph[key]}
}`
For example for search query `tesla` you get
![image](https://user-images.githubusercontent.com/64033139/170469800-897fe26d-7252-43d9-93ca-109c7c9306ea.png)
And for `apple`
![image](https://user-images.githubusercontent.com/64033139/170469878-04910000-e9fd-4e23-b25f-d9efdc8be0c6.png)

2022-05-26 11:20 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +*<span style="font-size: 15px;">If you don't have Node.js installed, you can download it from [here](https://nodejs.org/en/) and follow the installation [documentation](https://nodejs.dev/learn/intro
@Mykhailo-Zub interesting! Did you check that it will be supported on other platforms? dev.to/hashnode etc? Medium will not support it and default to regular text I guess.

2022-05-26 11:23 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +![how-2](https://serpapi.com/blog/content/images/2022/05/how-2.gif)
@Mykhailo-Zub 

Two ways:
1. don't care and forget about it.
2. record two separate gifs and combine them in post-production:
    - knowledge graph
    - panel thing
    
I personally wouldn't bother and choose the first way, _in the case where it won't fit in one area_.

2022-05-26 11:25 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +    const pattern = /s='(?<img>[^']+)';\w+\s\w+=\['(?<id>\w+_\d+)'];/gm;
My bad, you're right. I didn't notice it. 

Yes, let's added to the code itself also as people like me could also miss the link.

2022-05-26 11:26 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +|`$(".I6TXqe .VLkRKc").closest(".UDZeY")`|finds the nearest parent element with class name `UDZeY` in elements with class name `I6TXqe` that have elements with class names `VLkRKc`|
Make sense 👍🏻

2022-05-26 11:48 UTC, dimitryzub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +          allInfo.main = {...allInfo.main, [key]: knowledge_graph[key]}
@Mykhailo-Zub Makes sense, I misunderstood it 👍🏻 Good job, thank you for clarification. Please, write about it in the explanation section.

2022-05-26 12:58 UTC, Mykhailo-Zub commented on Google/google_organic_results/google_knowledge_graph/javascript/google_knowledge_graph.md
> +*<span style="font-size: 15px;">If you don't have Node.js installed, you can download it from [here](https://nodejs.org/en/) and follow the installation [documentation](https://nodejs.dev/learn/intro
@dimitryzub yes, you're right. Other platforms don't support `font-size`. But if only ghost.io supports it, I'll keep it.

2022-05-27 12:37 UTC, dimitryzub approved these changes
@Mykhailo-Zub Looks good, thank you 👍🏻 You can go ahead and merge this PR when you can.

2022-05-27 12:37 UTC, dimitryzub commented
Let's @set-reminder May 31 5am @Mykhailo-Zub, publish #15 blog post if you can.

2022-05-31 10:44 UTC, merged