eBay Organic Results
dimitryzub/serpapi-blog-posts-archive pull request #173
Opened 2022-06-06 08:54 UTC by Mykhailo-Zub

Resolves #171. [Draft](https://serpapi.com/blog/p/7b949e9b-baab-4d1c-879a-c1ce63985434/)

2022-06-07 05:53 UTC, dimitryzub requested changes
@Mykhailo-Zub Super good job! Thank you 👍🏻 

I've added a few minor suggestions. You can merge this PR once minor suggestions will be fixed and `@set-reminder` to June 13 to publish this blog post if you can.

2022-06-07 05:53 UTC, dimitryzub commented on eBay/ebay_organic_search/javascript/ebay_organic_results.md
> +First, we need to create a Node.js* project and add [`npm`](https://www.npmjs.com/) packages [`puppeteer`](https://www.npmjs.com/package/puppeteer), [`puppeteer-extra`](https://www.npmjs.com/package/
```suggestion
First, we need to create a Node.js* project and add [`npm`](https://www.npmjs.com/) packages [`puppeteer`](https://www.npmjs.com/package/puppeteer), [`puppeteer-extra`](https://www.npmjs.com/package/puppeteer-extra) and [`puppeteer-extra-plugin-stealth`](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth) to control Chromium (or Chrome, or Firefox, but now we work only with Chromium which is used by default) over the [DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) in [headless](https://developers.google.com/web/updates/2017/04/headless-chrome) or non-headless mode. 

To do this, in the directory with our project, open the command line and enter `npm init -y`, and then `npm i puppeteer puppeteer-extra puppeteer-extra-plugin-stealth`.
```

👍🏻 
Add a line separation and minor suggestion.

2022-06-07 05:53 UTC, dimitryzub commented on eBay/ebay_organic_search/javascript/ebay_organic_results.md
> +![stealth](https://user-images.githubusercontent.com/64033139/171674554-d6027d3e-5fb2-44fb-88c7-4492851b43ff.png)
👍🏻 Awesome! 

Could please add a drop shadow as well to this screenshot? So we have consistency across all screenshots.

2022-06-07 05:53 UTC, dimitryzub commented on eBay/ebay_organic_search/javascript/ebay_organic_results.md
> +      link: el.querySelector(".s-item__link").getAttribute("href"),
Could you also add a simple explanation about `querySelectorAll` and `querySelector` to cover everything in this part of the code?

2022-06-07 05:53 UTC, dimitryzub commented on eBay/ebay_organic_search/javascript/ebay_organic_results.md
> +|`browser.close()`|after all we close the browser instance|
Thank you! 💯 

I would also add a simple explanation about `if (!isNextPage || currentPage > pagesLimit) break;` to cover everything for non really familiar JS users or someone who's just starting out learning it.

Could you add a note that we can skip `page.keyboard.type(searchString)` and add search query directly in URL so there's no need to open the main page and then make the extra request to display product results.

2022-06-07 05:53 UTC, dimitryzub commented on eBay/ebay_organic_search/javascript/ebay_organic_results.md
> +|`price: price && price.raw ? price.raw : `${price.from?.raw} - ${price.to?.raw}``|in this line we use [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/C
```suggestion
|`price: price && price.raw ? price.raw : "${price.from?.raw} - ${price.to?.raw}"`|in this line we use [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) to set vailid price. If we can get `price` and data with `raw` key we set it to our `price`, otherwise in `price` we set `price.from` and `price.to`|
```

Can we change to `"` double quotes? There will be a conflict inside Markdown:


![image](https://user-images.githubusercontent.com/78694043/172304207-874f9dc0-41dc-4f44-aa10-79f40c3e7d6b.png)

2022-06-07 05:53 UTC, dimitryzub commented on eBay/ebay_organic_search/javascript/ebay_organic_results.md
> +      price: price && price.raw ? price.raw : `${price.from?.raw} - ${price.to?.raw}`,
```suggestion
      price: price && price.raw ? price.raw : "${price.from?.raw} - ${price.to?.raw}",
```

Can we change to `"` double quotes? There will be a conflict inside Markdown. See comment below.

![image](https://user-images.githubusercontent.com/78694043/172304290-3a265d0e-8be1-4183-9579-846dacf3f35b.png)

2022-06-10 08:56 UTC, Mykhailo-Zub commented on eBay/ebay_organic_search/javascript/ebay_organic_results.md
> +      price: price && price.raw ? price.raw : `${price.from?.raw} - ${price.to?.raw}`,
@dimitryzub I use [template string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). I can write this line like `price: price && price.raw ? price.raw : price.from?.raw + "-" + price.to?.raw,`, but its an old approach. So I think in multiline code snippet it looks don't so bad. What are you think?

2022-06-13 05:15 UTC, dimitryzub commented on eBay/ebay_organic_search/javascript/ebay_organic_results.md
> +      price: price && price.raw ? price.raw : `${price.from?.raw} - ${price.to?.raw}`,
@Mykhailo-Zub Got it 👍🏻 Let's leave it as you did it from the start without any changes as it looks more clear. Thank you 🤝

2022-06-13 05:18 UTC, dimitryzub approved these changes
@Mykhailo-Zub Thank you for the changes 🐱‍🏍

Everything looks good to me. Great explanation, thank you 🎉

You can go ahead and merge this PR when you can. Let's schedule this blog post for June 14.

I also removed from this PR [[Javascript] Ebay Content plan](https://github.com/dimitryzub/serpapi-blog-posts-archive/milestone/26) milestone. From now on, let's don't add Milestones to PRs, only to Issues. Otherwise, there will be duplication from the same Milestone which complicates things (issue + PR):

![image](https://user-images.githubusercontent.com/78694043/173352617-b740c14d-51eb-48a2-9e71-c7dad60860fa.png)

2022-06-13 05:20 UTC, dimitryzub commented
@set-reminder June 14 5am @Mykhailo-Zub if you can, publish #173 and leave blog post links in this thread 🌿

2022-06-14 08:21 UTC, merged