[Google Scholar] scrape organic results
dimitryzub/serpapi-blog-posts-archive pull request #23
Opened 2022-05-25 10:37 UTC by Mykhailo-Zub

Resolves #20 
[Draft](https://serpapi.com/blog/p/10f1b3fd-f2a8-4363-8ccf-8378ca00a606/)

2022-05-26 11:13 UTC, dimitryzub requested changes
@Mykhailo-Zub Awesome job! Really interesting 👍🏻 

There are a couple of things to make pretty, improve, and clarify.

2022-05-26 11:13 UTC, dimitryzub commented on Google/google_scholar/organic_cite_results/javascript/google-scholar-organic-results-scrape.md
> +function getScholarInfo() {
```suggestion
function getScholarOrganicResults() {
```

2022-05-26 11:13 UTC, dimitryzub commented on Google/google_scholar/organic_cite_results/javascript/google-scholar-organic-results-scrape.md
> +getScholarInfo().then(console.log);
```suggestion
getScholarOrganicResults().then(console.log);
```

2022-05-26 11:49 UTC, dimitryzub commented on Google/google_scholar/organic_cite_results/javascript/google-scholar-organic-results-scrape.md
> +*<span style="font-size: 15px;">If you don't have Node.js installed, you can download it from [here](https://nodejs.org/en/) and follow the installation [documentation](https://nodejs.dev/learn/intro
You can leave `<span>` element if it will be supported on other platforms such as dev.to/hashnode..

2022-05-26 14:25 UTC, Mykhailo-Zub commented on Google/google_scholar/organic_cite_results/javascript/google-scholar-organic-results-scrape.md
> +    hl: "en",                                                         // parameter defines the language to use for the Google search
@dimitryzub I'm of the opinion from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas)
>Trailing commas (sometimes called "final commas") can be useful when adding new elements, parameters, or properties to JavaScript code. If you want to add a new property, you can add a new line without modifying the previously last line if that line already uses a trailing comma. This makes version-control diffs cleaner and editing code might be less troublesome.

2022-05-26 14:42 UTC, Mykhailo-Zub commented on Google/google_scholar/organic_cite_results/javascript/google-scholar-organic-results-scrape.md
> +}
@dimitryzub, at first sight, it seems you're right, but some of these links can be absent. 
![image](https://user-images.githubusercontent.com/64033139/170510885-fe427328-8a1e-400e-bf90-bd28fa647423.png)
And axios also get something like this:
![image](https://user-images.githubusercontent.com/64033139/170511116-df279e76-f8c4-4791-b574-3ecf31ce03e7.png)
Thats why I use all from `buildValidLink` function.

2022-05-26 14:57 UTC, Mykhailo-Zub commented on Google/google_scholar/organic_cite_results/javascript/google-scholar-organic-results-scrape.md
> +![what-5](https://serpapi.com/blog/content/images/2022/05/what-5.png)
> Let me know if you'll add shadows to the previous blog posts.

@dimitryzub, no problem, I'll do this.

2022-05-27 12:43 UTC, dimitryzub commented on Google/google_scholar/organic_cite_results/javascript/google-scholar-organic-results-scrape.md
> +    hl: "en",                                                         // parameter defines the language to use for the Google search
@Mykhailo-Zub looks good to me. Didn't know, thank you for standing up with your opinion. 🥇

2022-05-27 12:44 UTC, dimitryzub commented on Google/google_scholar/organic_cite_results/javascript/google-scholar-organic-results-scrape.md
> +}
@Mykhailo-Zub makes sense. I'll then resolve these edits 👍🏻

2022-05-27 13:25 UTC, dimitryzub approved these changes
@Mykhailo-Zub Thank you for the edits 💯 Looks good to me.

You can go ahead and merge this PR when ready.

2022-05-27 13:27 UTC, dimitryzub commented
Let's set a reminder when to publish this blog post.

@set-reminder June 2 5am @Mykhailo-Zub if you can, publish #23 blog post, and add links to the published blog post here, in the comments thread 📡

2022-06-02 05:08 UTC, dimitryzub commented
@Mykhailo-Zub Let's take a little break on publishing blog posts for this week. We have published 4 blog posts this week. Let it be the maximum amount for the week.

Let's schedule these blog posts for the next week. @set-reminder June 7 5am @Mykhailo-Zub, publish #23 blog post if you can, and add links to the published blog post in the PR comments thread.

2022-06-02 05:09 UTC, dimitryzub commented
@set-reminder June 7 5am @Mykhailo-Zub, publish #23 blog post if you can, and add links to the published blog post in the PR comments thread.

2022-06-07 08:07 UTC, merged

2022-06-07 08:08 UTC, Mykhailo-Zub commented
https://serpapi.com/blog/how-to-scrape-google-scholar-organic-results-with-node-js/
https://medium.com/@mikhail.a.zub/how-to-scrape-google-scholar-organic-results-with-node-js-bbc4fe9fd330
https://dev.to/serpapi/how-to-scrape-google-scholar-organic-results-with-nodejs-4afm
https://serpapi.hashnode.dev/how-to-scrape-google-scholar-organic-results-with-nodejs