Google Scholar profiles
dimitryzub/serpapi-blog-posts-archive pull request #242
Opened 2022-06-21 07:54 UTC by Mykhailo-Zub

Resolves #175. [Draft](https://serpapi.com/blog/p/4ca36c41-4dda-4782-bb41-0b4562010a60/)

2022-06-24 10:28 UTC, dimitryzub requested changes
@Mykhailo-Zub Thank you so much for a good blog post 💪

There are a few minor things that catch my eyes.

2022-06-24 10:28 UTC, dimitryzub commented on Google/google_scholar/author_profile_results/javascript/profiles_results/google-scholar-profiles-results-scrape.md
> +const pagesLimit = 2;                                     // limit of pages for getting info
Same about the page limit as in the custom solution. Let's just show how to parse everything in the first place and add a comment on how to parse from X to Y page using page limit.

Let's do that for all of the APIs where there's pagination.

2022-06-24 10:28 UTC, dimitryzub commented on Google/google_scholar/author_profile_results/javascript/profiles_results/google-scholar-profiles-results-scrape.md
> +         },
I've run the code on replit and am not quite sure why the return value of `interests` is an `object`, the same in the SerpApi solution:

![image](https://user-images.githubusercontent.com/78694043/175516472-344b02a6-5dfc-41c2-ac0c-2e09b2d7a58a.png)

Is there anything I forgot to do? I haven't modified anything in the code.

2022-06-26 15:40 UTC, Mykhailo-Zub commented on Google/google_scholar/author_profile_results/javascript/profiles_results/google-scholar-profiles-results-scrape.md
> +         },
This happens because the depth of recursive reading of nested objects is 2 by default in Node.js console. I add an explanation before output.

2022-06-29 08:32 UTC, dimitryzub approved these changes
@Mykhailo-Zub Wonderful job! Thank you so much 🌞

You can go ahead and merge this PR/publish this blog post whenever you can. Please, leave links to the blog post in this PR thread as we did before.

2022-06-29 11:44 UTC, Mykhailo-Zub commented
https://serpapi.com/blog/how-to-scrape-google-scholar-profiles-results-with-node-js/
https://medium.com/@mikhail.a.zub/how-to-scrape-google-scholar-profiles-results-with-node-js-c1060479f68b
https://dev.to/serpapi/how-to-scrape-google-scholar-profiles-results-with-nodejs-4p92
https://serpapi.hashnode.dev/how-to-scrape-google-scholar-profiles-results-with-nodejs

2022-06-29 11:44 UTC, merged