Google Scholar author
dimitryzub/serpapi-blog-posts-archive pull request #243
Opened 2022-06-21 14:33 UTC by Mykhailo-Zub

Resolves #176. [Draft](https://serpapi.com/blog/p/9c7e783b-aff7-4a32-b656-b38f22cdc5f5/)

2022-06-24 11:11 UTC, dimitryzub requested changes
@Mykhailo-Zub Thank you so much! ⚡

I've added a few suggestions and for big suggestion changes, let's add all author articles extractions in this blog post also.

- author info
- all articles instead of articles from the first page
- graph
- co-authors

2022-06-24 11:11 UTC, dimitryzub commented on Google/google_scholar/author_profile_results/javascript/author_results/google-scholar-author-results-scrape.md
> +    articles: articles?.map((article) => {
Let's also scrape all author's articles in this blog post.

2022-06-24 11:11 UTC, dimitryzub commented on Google/google_scholar/author_profile_results/javascript/author_results/google-scholar-author-results-scrape.md
> +      articles: Array.from($(".gsc_a_tr")).map((el) => {
Let's also scrape all author's articles in this blog post.

2022-06-29 08:42 UTC, dimitryzub requested changes
@Mykhailo-Zub Thank you 🥇

One final thing, could you please update replit example for `puppeteer`? 

![image](https://user-images.githubusercontent.com/78694043/176392957-ddd7af79-c013-425e-9cea-65721f47292f.png)

2022-06-30 05:32 UTC, dimitryzub commented
@Mykhailo-Zub Thank you for the fix 👍 You can go ahead and merge this PR. Labeling this blog as accepted. Really good job, thank you.

Let's @set-reminder July 1 5am @Mykhailo-Zub publish #243 blog post if can.

2022-07-01 13:53 UTC, merged

2022-07-01 13:53 UTC, Mykhailo-Zub commented
https://serpapi.com/blog/how-to-scrape-google-author-with-node-js/
https://medium.com/@mikhail.a.zub/how-to-scrape-google-scholar-author-info-with-node-js-2c4114c73af9
https://dev.to/serpapi/how-to-scrape-google-scholar-author-info-with-nodejs-1b37
https://serpapi.hashnode.dev/how-to-scrape-google-scholar-author-info-with-nodejs