Google Scholar Cite
dimitryzub/serpapi-blog-posts-archive pull request #244
Opened 2022-07-07 16:14 UTC by Mykhailo-Zub

Resolves #174. [Draft](https://serpapi.com/blog/p/2645ec01-c628-4f52-97e0-653af5b660f0/)

2022-07-09 07:32 UTC, dimitryzub requested changes
@Mykhailo-Zub Thank you for the quality step-by-step tutorial blog post 💯

On replit, when individual cite results are being parsed, after extracting cite ID I get error but it seems to be a replit thing:
![image](https://user-images.githubusercontent.com/78694043/178096362-815d7c30-e514-4d84-afb5-69451402a0c5.png)

There're also a few minor things I've noticed.

2022-07-09 07:32 UTC, dimitryzub commented on Google/google_scholar/organic_cite_results/javascript/cite_results/google-scholar-cite-results-scrape.md
> +|`hl`|parameter defines the language to use for the Google search|
```suggestion
|`hl`|parameter defines the language to use for the Google Scholar search|
```

2022-07-09 07:32 UTC, dimitryzub commented on Google/google_scholar/organic_cite_results/javascript/cite_results/google-scholar-cite-results-scrape.md
> +📌Note: if you see something like `[Object]` in your console you can use `console.dir(result, { depth: null })` instead `console.log()`. Watch [Node.js documentation](https://nodejs.org/api/console.ht
👍👍

2022-07-09 07:32 UTC, dimitryzub commented on Google/google_scholar/organic_cite_results/javascript/cite_results/google-scholar-cite-results-scrape.md
> +* [Google Scholar API](https://serpapi.com/google-scholar-api)
```suggestion
* [Google Scholar Cite API](https://serpapi.com/google-scholar-cite-api)
```

2022-07-10 14:47 UTC, Mykhailo-Zub commented
> On replit, when individual cite results are being parsed, after extracting cite ID I get error but it seems to be a replit thing:

@dimitryzub I wrapped this code in `try-catch` to prevent crashing the script if we get some error.

2022-07-11 08:39 UTC, dimitryzub approved these changes
@Mykhailo-Zub Looks good 💯Thank you!

You can publish this blog post whenever you can and merge this PR. Would it be possible to publish it this week (July 11-15)?

2022-07-12 07:35 UTC, merged

2022-07-12 07:35 UTC, Mykhailo-Zub commented
https://serpapi.com/blog/how-to-scrape-google-scholar-cite-with-nodejs/
https://medium.com/@mikhail.a.zub/web-scraping-google-scholar-cite-results-with-nodejs-64abef8da369
https://dev.to/serpapi/web-scraping-google-scholar-cite-results-with-nodejs-3ncg
https://serpapi.hashnode.dev/web-scraping-google-scholar-cite-results-with-nodejs